<?php
/**
 * CheckoutFormFulfillmentStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * CheckoutFormFulfillmentStatus Class Doc Comment
 *
 * @category Class
 * @description Order seller status.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CheckoutFormFulfillmentStatus
{
    /**
     * Possible values of this enum
     */
    const _NEW = 'NEW';
const PROCESSING = 'PROCESSING';
const READY_FOR_SHIPMENT = 'READY_FOR_SHIPMENT';
const READY_FOR_PICKUP = 'READY_FOR_PICKUP';
const SENT = 'SENT';
const PICKED_UP = 'PICKED_UP';
const CANCELLED = 'CANCELLED';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
self::PROCESSING,
self::READY_FOR_SHIPMENT,
self::READY_FOR_PICKUP,
self::SENT,
self::PICKED_UP,
self::CANCELLED,        ];
    }
}
