<?php
/**
 * OfferStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * OfferStatus Class Doc Comment
 *
 * @category Class
 * @description The publication status of the current offer. The possible values:    - *INACTIVE* - a draft offer   - *ACTIVATING* - the offer is planned for listing or is during the process of activation   - *ACTIVE* - the offer is active   - *ENDED* - the offer was active and is now ended (for whatever reason)
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OfferStatus
{
    /**
     * Possible values of this enum
     */
    const INACTIVE = 'INACTIVE';
const ACTIVATING = 'ACTIVATING';
const ACTIVE = 'ACTIVE';
const ENDED = 'ENDED';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INACTIVE,
self::ACTIVATING,
self::ACTIVE,
self::ENDED,        ];
    }
}
