<?php
/**
 * CategoryParameterOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CategoryParameterOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description A list of the different options which can be used with this parameter.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CategoryParameterOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CategoryParameterOptions"
     */
    public function testCategoryParameterOptions()
    {
    }

    /**
     * Test attribute "variants_allowed"
     */
    public function testPropertyVariantsAllowed()
    {
    }

    /**
     * Test attribute "variants_equal"
     */
    public function testPropertyVariantsEqual()
    {
    }

    /**
     * Test attribute "ambiguous_value_id"
     */
    public function testPropertyAmbiguousValueId()
    {
    }

    /**
     * Test attribute "depends_on_parameter_id"
     */
    public function testPropertyDependsOnParameterId()
    {
    }

    /**
     * Test attribute "required_depends_on_value_ids"
     */
    public function testPropertyRequiredDependsOnValueIds()
    {
    }

    /**
     * Test attribute "display_depends_on_value_ids"
     */
    public function testPropertyDisplayDependsOnValueIds()
    {
    }

    /**
     * Test attribute "describes_product"
     */
    public function testPropertyDescribesProduct()
    {
    }

    /**
     * Test attribute "custom_values_enabled"
     */
    public function testPropertyCustomValuesEnabled()
    {
    }
}
