<?php
/**
 * ProductParameterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductParameterTest Class Doc Comment
 *
 * @category    Class
 * @description Product&#x27;s parameter
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductParameterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductParameter"
     */
    public function testProductParameter()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "range_value"
     */
    public function testPropertyRangeValue()
    {
    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {
    }

    /**
     * Test attribute "values_ids"
     */
    public function testPropertyValuesIds()
    {
    }

    /**
     * Test attribute "values_labels"
     */
    public function testPropertyValuesLabels()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }
}
