<?php
/**
 * ReturnPolicyOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReturnPolicyOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description ReturnPolicyOptions
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReturnPolicyOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReturnPolicyOptions"
     */
    public function testReturnPolicyOptions()
    {
    }

    /**
     * Test attribute "cash_on_delivery_not_allowed"
     */
    public function testPropertyCashOnDeliveryNotAllowed()
    {
    }

    /**
     * Test attribute "free_accessories_return_required"
     */
    public function testPropertyFreeAccessoriesReturnRequired()
    {
    }

    /**
     * Test attribute "refund_lowered_by_received_discount"
     */
    public function testPropertyRefundLoweredByReceivedDiscount()
    {
    }

    /**
     * Test attribute "business_return_allowed"
     */
    public function testPropertyBusinessReturnAllowed()
    {
    }

    /**
     * Test attribute "collect_by_seller_only"
     */
    public function testPropertyCollectBySellerOnly()
    {
    }

    /**
     * Test attribute "abroad_return_terms_may_differ"
     */
    public function testPropertyAbroadReturnTermsMayDiffer()
    {
    }
}
