<?php
/**
 * UserRatingSummaryResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserRatingSummaryResponseTest Class Doc Comment
 *
 * @category    Class
 * @description UserRatingSummaryResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserRatingSummaryResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserRatingSummaryResponse"
     */
    public function testUserRatingSummaryResponse()
    {
    }

    /**
     * Test attribute "average_rates"
     */
    public function testPropertyAverageRates()
    {
    }

    /**
     * Test attribute "not_recommended"
     */
    public function testPropertyNotRecommended()
    {
    }

    /**
     * Test attribute "recommended"
     */
    public function testPropertyRecommended()
    {
    }

    /**
     * Test attribute "recommended_percentage"
     */
    public function testPropertyRecommendedPercentage()
    {
    }
}
