<?php
/**
 * CompatibilityListApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * CompatibilityListApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CompatibilityListApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCategoriesThatSupportCompatibilityList
     *
     * Get list of categories where compatibility list is supported.
     *
     */
    public function testGetCategoriesThatSupportCompatibilityList()
    {
    }

    /**
     * Test case for getCompatibilityListSuggestion
     *
     * Get suggested compatibility list..
     *
     */
    public function testGetCompatibilityListSuggestion()
    {
    }

    /**
     * Test case for getCompatibleProducts
     *
     * Get list of compatible products.
     *
     */
    public function testGetCompatibleProducts()
    {
    }

    /**
     * Test case for getCompatibleProductsGroups
     *
     * Get list of compatible product groups.
     *
     */
    public function testGetCompatibleProductsGroups()
    {
    }
}
