<?php
/**
 * MessageCenterApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MessageCenterApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessageCenterApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changeReadFlagOnThreadPUT
     *
     * Mark a particular thread as read.
     *
     */
    public function testChangeReadFlagOnThreadPUT()
    {
    }

    /**
     * Test case for deleteMessageDELETE
     *
     * Delete single message.
     *
     */
    public function testDeleteMessageDELETE()
    {
    }

    /**
     * Test case for downloadAttachmentGET
     *
     * Download attachment.
     *
     */
    public function testDownloadAttachmentGET()
    {
    }

    /**
     * Test case for getMessageGET
     *
     * Get single message.
     *
     */
    public function testGetMessageGET()
    {
    }

    /**
     * Test case for getThreadGET
     *
     * Get user thread.
     *
     */
    public function testGetThreadGET()
    {
    }

    /**
     * Test case for listMessagesGET
     *
     * List messages in thread.
     *
     */
    public function testListMessagesGET()
    {
    }

    /**
     * Test case for listThreadsGET
     *
     * List user threads.
     *
     */
    public function testListThreadsGET()
    {
    }

    /**
     * Test case for newAttachmentDeclarationPOST
     *
     * Add attachment declaration.
     *
     */
    public function testNewAttachmentDeclarationPOST()
    {
    }

    /**
     * Test case for newMessageInThreadPOST
     *
     * Write a new message in thread.
     *
     */
    public function testNewMessageInThreadPOST()
    {
    }

    /**
     * Test case for newMessagePOST
     *
     * Write a new message.
     *
     */
    public function testNewMessagePOST()
    {
    }

    /**
     * Test case for uploadAttachmentPUT
     *
     * Upload attachment binary data.
     *
     */
    public function testUploadAttachmentPUT()
    {
    }
}
