<?php
/**
 * OfferManagementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * OfferManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OfferManagementApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changePublicationStatusUsingPUT
     *
     * Batch offer publish / unpublish.
     *
     */
    public function testChangePublicationStatusUsingPUT()
    {
    }

    /**
     * Test case for createChangePriceCommandUsingPUT
     *
     * Modify the Buy Now price in an offer.
     *
     */
    public function testCreateChangePriceCommandUsingPUT()
    {
    }

    /**
     * Test case for createOfferUsingPOST
     *
     * Create a draft offer.
     *
     */
    public function testCreateOfferUsingPOST()
    {
    }

    /**
     * Test case for createProductOffers
     *
     * Create offer based on product.
     *
     */
    public function testCreateProductOffers()
    {
    }

    /**
     * Test case for deleteOfferUsingDELETE
     *
     * Delete a draft offer.
     *
     */
    public function testDeleteOfferUsingDELETE()
    {
    }

    /**
     * Test case for editProductOffers
     *
     * Edit an offer.
     *
     */
    public function testEditProductOffers()
    {
    }

    /**
     * Test case for getAvailableOfferPromotionPackages
     *
     * Get all available offer promotion packages.
     *
     */
    public function testGetAvailableOfferPromotionPackages()
    {
    }

    /**
     * Test case for getOfferPromoOptionsUsingGET
     *
     * Get offer promotion packages.
     *
     */
    public function testGetOfferPromoOptionsUsingGET()
    {
    }

    /**
     * Test case for getOffersUnfilledParametersUsingGET1
     *
     * Get offers with missing parameters.
     *
     */
    public function testGetOffersUnfilledParametersUsingGET1()
    {
    }

    /**
     * Test case for getProductOffer
     *
     * Get all data of the particular product-offer.
     *
     */
    public function testGetProductOffer()
    {
    }

    /**
     * Test case for getProductOfferProcessingStatus
     *
     * Check the processing status of a POST or PATCH request.
     *
     */
    public function testGetProductOfferProcessingStatus()
    {
    }

    /**
     * Test case for getPromoModificationCommandDetailedResultUsingGET
     *
     * Modification command detailed result.
     *
     */
    public function testGetPromoModificationCommandDetailedResultUsingGET()
    {
    }

    /**
     * Test case for getPromoModificationCommandResultUsingGET
     *
     * Modification command summary.
     *
     */
    public function testGetPromoModificationCommandResultUsingGET()
    {
    }

    /**
     * Test case for getPublicationReportUsingGET
     *
     * Publish command summary.
     *
     */
    public function testGetPublicationReportUsingGET()
    {
    }

    /**
     * Test case for getPublicationTasksUsingGET
     *
     * Publish command detailed report.
     *
     */
    public function testGetPublicationTasksUsingGET()
    {
    }

    /**
     * Test case for modifyOfferPromoOptionsUsingPOST
     *
     * Modify offer promotion packages.
     *
     */
    public function testModifyOfferPromoOptionsUsingPOST()
    {
    }

    /**
     * Test case for promoModificationCommandUsingPUT
     *
     * Batch offer promotion package modification.
     *
     */
    public function testPromoModificationCommandUsingPUT()
    {
    }

    /**
     * Test case for updateOfferUsingPUT
     *
     * Complete a draft offer or edit an offer.
     *
     */
    public function testUpdateOfferUsingPUT()
    {
    }
}
